# Generated by Django 3.0 on 2024-06-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_auto_20240603_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='image',
            new_name='adminimage',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='is_staff',
            new_name='is_employee',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='mobile',
            new_name='mobilenumber',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='categoryslug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='categorytitle',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='mobilenumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mobile',
            new_name='mobilenumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='productorderedby',
            new_name='orderby',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoryname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='productdescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='productimage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productprice',
            new_name='productprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='productslug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='producttitle',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='joined_on',
        ),
        migrations.AlterField(
            model_name='order',
            name='ostatus',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
