# Generated by Django 3.0 on 2024-06-03 04:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_auto_20240602_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='adminimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='is_employee',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='mobilenumber',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryslug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categorytitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobilenumber',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mobilenumber',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderby',
            new_name='productorderedby',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='shipping_address',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoryname',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productprice',
            new_name='productprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productslug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='producttitle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='customer',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ostatus',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Product')),
            ],
        ),
    ]
